# Generated by Django 3.0.5 on 2026-04-08 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the portal.')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DocEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('view_name', models.CharField(blank=True, max_length=255)),
                ('app_label', models.CharField(help_text='Django app this endpoint belongs to (e.g. astra, locci).', max_length=100)),
                ('summary', models.CharField(blank=True, help_text='First line of the view docstring. Auto-populated by syncdocs.', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Full docstring text. Auto-populated by syncdocs, editable by managers.')),
                ('published', models.BooleanField(default=True, help_text='Unpublished endpoints are hidden from the portal but still function.')),
                ('is_orphan', models.BooleanField(default=False, help_text='Set by syncdocs when this path no longer exists in the URL configuration.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='docca.DocTag')),
            ],
            options={
                'ordering': ('path', 'method'),
                'unique_together': {('path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='DocParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('query', 'Query'), ('path', 'Path'), ('body', 'Body')], default='query', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('example', models.CharField(blank=True, max_length=500)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='docca.DocEndpoint')),
            ],
            options={
                'ordering': ('location', 'name'),
                'unique_together': {('endpoint', 'name', 'location')},
            },
        ),
    ]
