# Generated by Django 3.0.5 on 2026-04-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docendpoint',
            name='overview',
            field=models.TextField(blank=True, help_text='Product-facing description written by managers. Never overwritten by syncdocs. Shown prominently in the portal.'),
        ),
    ]
