# Generated by Django 3.0.5 on 2026-04-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docca', '0003_add_parameter_def'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocResponseField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('object', 'Object'), ('array', 'Array'), ('datetime', 'Datetime')], default='string', max_length=20)),
                ('nullable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Description of this field in the context of this endpoint. Never overwritten by syncdocs.')),
                ('example', models.CharField(blank=True, help_text='Example value as it appears in a real response.', max_length=500)),
            ],
            options={
                'verbose_name': 'response field',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='docparameter',
            name='unique_endpoint_param_location',
        ),
        migrations.AlterField(
            model_name='docparameter',
            name='description_override',
            field=models.TextField(blank=True, help_text='Leave blank to use the canonical description from the parameter definition.'),
        ),
        migrations.AlterField(
            model_name='docparameterdef',
            name='description',
            field=models.TextField(blank=True, help_text='Canonical description shown on all endpoints that use this parameter. Write once, inherited everywhere.'),
        ),
        migrations.AlterUniqueTogether(
            name='docparameter',
            unique_together={('endpoint', 'param_def', 'location')},
        ),
        migrations.AddField(
            model_name='docresponsefield',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_fields', to='docca.DocEndpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='docresponsefield',
            unique_together={('endpoint', 'name')},
        ),
    ]
