# Generated by Django 3.0.5 on 2026-04-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotta', '0002_rename_anon_fields'),
        ('reggi', '0002_add_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Rate-limit tier for this key. Overrides the user-level tier when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='kotta.Tier'),
        ),
    ]
