# Generated by Django 3.0.5 on 2026-04-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reggi', '0003_apikey_tier'),
        ('kotta', '0002_rename_anon_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagecounter',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='reggi.ApiKey'),
        ),
    ]
